log4j.rootLogger=INFO, FileAppender, ConsoleAppender

# ===== \u6587\u4EF6 Appender =====
log4j.appender.FileAppender=org.apache.log4j.FileAppender
log4j.appender.FileAppender.File=./src/test/resources/logs/applog.txt
log4j.appender.FileAppender.Append=false
log4j.appender.FileAppender.ImmediateFlush=true
log4j.appender.FileAppender.Threshold=INFO
log4j.appender.FileAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.FileAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%t] %c{1} - %m%n

# ===== \u63A7\u5236\u53F0 Appender =====
log4j.appender.ConsoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.ConsoleAppender.Threshold=INFO
log4j.appender.ConsoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.ConsoleAppender.layout.ConversionPattern=[%c{1}] [%-5p] %m%n