searchbox=//textarea[@id='APjFqb']
loginid=input[id='identifierId']


#Bank Manager Login Test
bankmanager_css=button[ng-click='manager()']
bankmanager_add_customer_css=button[ng-click='addCust()']

#Add bank customer
bankcustomer_firstname_xpath=//input[@ng-model='fName']
bankcustomer_lastname_xpath=//input[@ng-model='lName']
bankcustomer_ps_xpath=//input[@ng-model='postCd']
bankcustomer_button_css=button[type='submit']

#Open Account
bankmanager_click_openaccount_css=button[ng-click='openAccount()']
bankcustomer_openaccount_css=select#userSelect
bankcustomer_currency_css=select#currency
bankcustomer_submit_xpath=//button[@type='submit']
